feature/sc-29642-import-elasticache-to-iac
StuDocu/terraform-aws-elasticache-redis pull request #1
Opened 2022-09-19 13:22 UTC by AlexPiko

- new main.tf and variables.tf
- new Jenkinsfile to merge and release

2022-09-19 14:02 UTC, g4rb1 requested changes

2022-09-19 14:31 UTC, AlexPiko commented on main.tf
> +  security_group_ids = var.security_group_ids
[76ce1da](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/76ce1da98c64f33e5f6da2081bf6c0e2ed365996)

2022-09-19 14:31 UTC, AlexPiko commented on main.tf
> +  subnet_group_name  = var.subnet_group_name
[76ce1da](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/76ce1da98c64f33e5f6da2081bf6c0e2ed365996)

2022-09-20 07:49 UTC, g4rb1 requested changes

2022-09-20 07:49 UTC, g4rb1 commented on example/main.tf
> +    workspaces {
this needs to be removed since its only works with Terraform Cloud.
We are going to use Spacelift now

2022-09-20 07:49 UTC, g4rb1 commented on variables.tf
> +variable "vpc_security_group_ids" {
can we remove the `vpc_` prefix, just to be consistent with the name of the real entry? Sorry this was my fault

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  node_type                  = "cache.r6g.xlarge"
`node_type should be a variable

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  num_cache_clusters   = 2
this should be a variable

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  multi_az_enabled           = true
should be a variable

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  automatic_failover_enabled = true
should be a variable

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  transit_encryption_enabled = false
should be a variable

2022-09-20 07:49 UTC, g4rb1 commented on main.tf
> +  description                = "Redis replication group"
should be a variable

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  description                = "Redis replication group"
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  transit_encryption_enabled = false
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  automatic_failover_enabled = true
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  multi_az_enabled           = true
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  num_cache_clusters   = 2
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on main.tf
> +  node_type                  = "cache.r6g.xlarge"
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-20 09:26 UTC, AlexPiko commented on variables.tf
> +variable "vpc_security_group_ids" {
[3166551](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/3166551966f94b702ee9fdc93ac20d5670124cc2)

2022-09-21 13:36 UTC, AlexPiko commented on example/main.tf
> +  subnet_ids                 = data.aws_subnets.PrivateSubnets.ids
[faa1b59](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/faa1b59090a4d98d4a662322d18ca23a5f69922e)

2022-09-21 13:36 UTC, AlexPiko commented on example/main.tf
> +data "aws_subnets" "PrivateSubnets" {
[faa1b59](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/faa1b59090a4d98d4a662322d18ca23a5f69922e)

2022-09-21 13:36 UTC, AlexPiko commented on example/main.tf
> +  assume_role {
[faa1b59](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/faa1b59090a4d98d4a662322d18ca23a5f69922e)

2022-09-21 13:36 UTC, AlexPiko commented on example/main.tf
> +  backend "remote" {
[faa1b59](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/faa1b59090a4d98d4a662322d18ca23a5f69922e)

2022-09-21 13:37 UTC, AlexPiko commented on README.md
> +<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
Yes that was the missing part to make the hook work properly [161d506](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/161d506e9a1cbde9653626cfceb5ef9d035649ee)

2022-09-21 14:08 UTC, g4rb1 commented
Can you please add a `.gitignore` copy it from the elastic beanstalk module

2022-09-21 14:11 UTC, g4rb1 requested changes

2022-09-21 14:11 UTC, g4rb1 commented on README.md
> +  node_type                  = "cache.r6g.xlarge"
lets use the cheapest one, since this one will be deployed every time as part of the test

2022-09-21 14:11 UTC, g4rb1 commented on README.md
> +  multi_az_enabled           = true
```suggestion
  multi_az_enabled           = false
```

2022-09-21 14:30 UTC, g4rb1 requested changes

2022-09-21 14:30 UTC, g4rb1 commented on variables.tf
> +  type        = string
This one must be bool

2022-09-21 14:46 UTC, AlexPiko commented on variables.tf
> +  type        = string
[e184922](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/e184922908b833457ded0faac682bb05641e0866)

2022-09-21 15:00 UTC, AlexPiko commented on README.md
> +  multi_az_enabled           = true
[ee22d2e](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/ee22d2eebbdeefe974a2ce28533b35359023e42b)

2022-09-21 15:01 UTC, AlexPiko commented on README.md
> +  node_type                  = "cache.r6g.xlarge"
[ee22d2e](https://github.com/StuDocu/terraform-aws-elasticache-redis/pull/1/commits/ee22d2eebbdeefe974a2ce28533b35359023e42b)

2022-09-27 11:49 UTC, g4rb1 approved these changes

2022-09-27 11:49 UTC, merged